//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ComparatorReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://achilles.tu.kielce.pl", ConfigurationName="ComparatorReference.IComparatorService")]
    public interface IComparatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://achilles.tu.kielce.pl/IComparatorService/joinToServer", ReplyAction="http://achilles.tu.kielce.pl/IComparatorService/joinToServerResponse")]
        WcfServiceLibrary1.ServerOptions joinToServer(WcfServiceLibrary1.JoinToServerCommand joinToServerCommand);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://achilles.tu.kielce.pl/IComparatorService/fetchFilesToCompare", ReplyAction="http://achilles.tu.kielce.pl/IComparatorService/fetchFilesToCompareResponse")]
        WcfServiceLibrary1.FilesToCompare fetchFilesToCompare(string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://achilles.tu.kielce.pl/IComparatorService/downloadFile", ReplyAction="http://achilles.tu.kielce.pl/IComparatorService/downloadFileResponse")]
        System.IO.Stream downloadFile(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://achilles.tu.kielce.pl/IComparatorService/finishComparing", ReplyAction="http://achilles.tu.kielce.pl/IComparatorService/finishComparingResponse")]
        void finishComparing(WcfServiceLibrary1.ComparingResult comparingResult);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://achilles.tu.kielce.pl/IComparatorService/heartbeat", ReplyAction="http://achilles.tu.kielce.pl/IComparatorService/heartbeatResponse")]
        void heartbeat(string uuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComparatorServiceChannel : Client.ComparatorReference.IComparatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComparatorServiceClient : System.ServiceModel.ClientBase<Client.ComparatorReference.IComparatorService>, Client.ComparatorReference.IComparatorService {
        
        public ComparatorServiceClient() {
        }
        
        public ComparatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComparatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComparatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComparatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfServiceLibrary1.ServerOptions joinToServer(WcfServiceLibrary1.JoinToServerCommand joinToServerCommand) {
            return base.Channel.joinToServer(joinToServerCommand);
        }
        
        public WcfServiceLibrary1.FilesToCompare fetchFilesToCompare(string uuid) {
            return base.Channel.fetchFilesToCompare(uuid);
        }
        
        public System.IO.Stream downloadFile(string fileName) {
            return base.Channel.downloadFile(fileName);
        }
        
        public void finishComparing(WcfServiceLibrary1.ComparingResult comparingResult) {
            base.Channel.finishComparing(comparingResult);
        }
        
        public void heartbeat(string uuid) {
            base.Channel.heartbeat(uuid);
        }
    }
}
